SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

ALTER TABLE `lld201407`.`users` 
ADD COLUMN `genders_idgender` INT(11) NOT NULL AFTER `gender`,
ADD INDEX `fk_users_genders1_idx` (`genders_idgender` ASC);

ALTER TABLE `lld201407`.`users` 
ADD CONSTRAINT `fk_users_genders1`
  FOREIGN KEY (`genders_idgender`)
  REFERENCES `lld201407`.`genders` (`idgender`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
